// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcKzZwFjEJ9YReDF3znLRcbtQWmrwWck4',
    appId: '1:739062395077:web:43023ff7ebdf21dca400ac',
    messagingSenderId: '739062395077',
    projectId: 'flutter-projects-6edb8',
    authDomain: 'flutter-projects-6edb8.firebaseapp.com',
    storageBucket: 'flutter-projects-6edb8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjGrd6Dn1AZ13M7hP-r49Stw-EiVEiq6I',
    appId: '1:739062395077:android:fffeabb448908bf6a400ac',
    messagingSenderId: '739062395077',
    projectId: 'flutter-projects-6edb8',
    storageBucket: 'flutter-projects-6edb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_I2_wLzh2jA6D-dpcU3ZXK_nRXS_WBzA',
    appId: '1:739062395077:ios:24e16dea2b141057a400ac',
    messagingSenderId: '739062395077',
    projectId: 'flutter-projects-6edb8',
    storageBucket: 'flutter-projects-6edb8.firebasestorage.app',
    iosClientId: '739062395077-vj5unbmbk2laued6rl5upvib3bj7vhnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.evertecTechnicalTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_I2_wLzh2jA6D-dpcU3ZXK_nRXS_WBzA',
    appId: '1:739062395077:ios:24e16dea2b141057a400ac',
    messagingSenderId: '739062395077',
    projectId: 'flutter-projects-6edb8',
    storageBucket: 'flutter-projects-6edb8.firebasestorage.app',
    iosClientId: '739062395077-vj5unbmbk2laued6rl5upvib3bj7vhnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.evertecTechnicalTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcKzZwFjEJ9YReDF3znLRcbtQWmrwWck4',
    appId: '1:739062395077:web:43023ff7ebdf21dca400ac',
    messagingSenderId: '739062395077',
    projectId: 'flutter-projects-6edb8',
    authDomain: 'flutter-projects-6edb8.firebaseapp.com',
    storageBucket: 'flutter-projects-6edb8.firebasestorage.app',
  );
}
